// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znvbqaywbqhoetshlzrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpudmJxYXl3YnFob2V0c2hsenJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODMwNjksImV4cCI6MjA1MzU1OTA2OX0.R0Sy33lwphk2yQczQhIPZjp4jklt0vt1B0Jb6UuqjZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);